/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Galactus
 */
public class ECgui extends javax.swing.JFrame {

    /**
     * Creates new form ECgui
     */
    public ECgui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crossoverTxt = new javax.swing.JTextField();
        crossLbl = new javax.swing.JLabel();
        mutationLbl = new javax.swing.JLabel();
        generaLbl = new javax.swing.JLabel();
        mutationTxt = new javax.swing.JTextField();
        generationTxt = new javax.swing.JTextField();
        xValuesTxt = new javax.swing.JTextField();
        xValuesLbl = new javax.swing.JLabel();
        yValuesLbl = new javax.swing.JLabel();
        yValuesTxt = new javax.swing.JTextField();
        runBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EC Curve Fitting");
        setName("ecJFrame"); // NOI18N

        crossoverTxt.setColumns(4);
        crossoverTxt.setText("85");
        crossoverTxt.setToolTipText("Rate as %, without % sign");

        crossLbl.setText("Crossover rate");
        crossLbl.setToolTipText("Rate as %, without % sign");

        mutationLbl.setText("Mutation rate");
        mutationLbl.setToolTipText("Rate as %, without % sign");

        generaLbl.setText("Generation size");
        generaLbl.setToolTipText("Population of each generation");

        mutationTxt.setColumns(4);
        mutationTxt.setText("5");
        mutationTxt.setToolTipText("Rate as %, without % sign");
        mutationTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mutationTxtActionPerformed(evt);
            }
        });

        generationTxt.setText("50");
        generationTxt.setToolTipText("Population size of each generation");

        xValuesTxt.setText("values separated with commas or spaces");
        xValuesTxt.setToolTipText("Enter values separated with commas or spaces");

        xValuesLbl.setText("Training input values");

        yValuesLbl.setText("Traiing output values");

        yValuesTxt.setText("values separated with commas or spaces");
        yValuesTxt.setToolTipText("Enter values separated with commas or spaces");

        runBtn.setText("Run");
        runBtn.setToolTipText("Execute with given parameters");

        resetBtn.setText("Reset");
        resetBtn.setToolTipText("Clear fields to original state");

        closeBtn.setText("Close");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xValuesLbl)
                    .addComponent(yValuesLbl)
                    .addComponent(xValuesTxt)
                    .addComponent(yValuesTxt)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mutationLbl)
                                    .addComponent(generaLbl))
                                .addGap(5, 5, 5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(crossLbl)
                                .addGap(9, 9, 9)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(crossoverTxt)
                            .addComponent(generationTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mutationTxt, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(runBtn)
                        .addGap(89, 89, 89)
                        .addComponent(resetBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                        .addComponent(closeBtn)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crossoverTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crossLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mutationLbl)
                    .addComponent(mutationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generaLbl)
                    .addComponent(generationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(xValuesLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xValuesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yValuesLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yValuesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runBtn)
                    .addComponent(resetBtn)
                    .addComponent(closeBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mutationTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mutationTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mutationTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ECgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ECgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ECgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ECgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ECgui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel crossLbl;
    private javax.swing.JTextField crossoverTxt;
    private javax.swing.JLabel generaLbl;
    private javax.swing.JTextField generationTxt;
    private javax.swing.JLabel mutationLbl;
    private javax.swing.JTextField mutationTxt;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton runBtn;
    private javax.swing.JLabel xValuesLbl;
    private javax.swing.JTextField xValuesTxt;
    private javax.swing.JLabel yValuesLbl;
    private javax.swing.JTextField yValuesTxt;
    // End of variables declaration//GEN-END:variables
}
